2025-08-17 18:39:53,944 -- ERROR -- scraping -- Error during scraping: Mercado_Libre_Object.__init__() got an unexpected keyword argument 'seller_id'
2025-08-17 18:40:34,680 -- ERROR -- scraping -- Error during scraping: 'Mercado_Libre_Object' object has no attribute 'seller_id'
2025-08-17 19:14:34,922 -- ERROR -- scraping -- Error during scraping: Message: 
Stacktrace:
#0 0x55f705f8c05a <unknown>
#1 0x55f705a2ba70 <unknown>
#2 0x55f705a7d907 <unknown>
#3 0x55f705a7db01 <unknown>
#4 0x55f705acbd54 <unknown>
#5 0x55f705aa340d <unknown>
#6 0x55f705ac914f <unknown>
#7 0x55f705aa31b3 <unknown>
#8 0x55f705a6f59b <unknown>
#9 0x55f705a70971 <unknown>
#10 0x55f705f5122b <unknown>
#11 0x55f705f54f79 <unknown>
#12 0x55f705f38309 <unknown>
#13 0x55f705f55b28 <unknown>
#14 0x55f705f1cbef <unknown>
#15 0x55f705f790e8 <unknown>
#16 0x55f705f792c6 <unknown>
#17 0x55f705f8b036 <unknown>
#18 0x7fa9f8f8bac3 <unknown>

2025-09-02 11:27:29,375 -- ERROR -- mongo_manager -- Failed to create document in collection Items: type object 'datetime.datetime' has no attribute 'timezone'
2025-09-02 11:29:08,286 -- ERROR -- mongo_manager -- Failed to create document in collection Items: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68b71b1e8d1bd7dcf8eb3229, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-09-02 11:30:48,425 -- ERROR -- mongo_manager -- Failed to create document in collection Items: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68b71b81efbbaed36e13cca6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
